---


- name: Clone the git repository associated with the Flask project
  git:
    repo: "{{ flask_project_repo_url }}"
    version: "{{ flask_project_repo_version }}"
    dest: "{{ flask_project_path }}"
    accept_hostkey: yes
    recursive: no
    force: yes
    key_file: "{{ deploy_key_filepath|default('') }}"
  register: gitclone

- name: Ensure that the project files can be accessed by the flask files group (www-data)
  file:
    path: "{{ flask_project_path }}"
    state: directory
    group: www-data
    recurse: yes
    mode: "u=rwX,g=rX,o="
  changed_when: false

- include: trigger_reload.yml
  when: gitclone.changed
