---


- name: Create .env.json settings file
  copy:
    content: "{{ flask_jsonsettings_properties }}"
    dest: "{{ flask_path }}/.env.json"
  register: env_json_config_content

- include: trigger_reload.yml
  when: env_json_config_content is changed
