---


- name: Ensure that the Flask project's user exists and is in the www-data group
  user:
    name: "{{ flask_user }}"
    createhome: yes
    shell: /bin/bash
    append: yes
    groups: www-data
    generate_ssh_key: yes

- name: Ensure that our base project path has proper permissions
  file:
    path: "{{ flask_path }}"
    state: directory
    owner: "{{ flask_user }}"
    group: www-data
    mode: ug=rwx,o=

- block:
  - set_fact:
      deploy_key_filepath: "/home/{{ flask_user }}/.ssh/deploy_key"

  - name: Send private deploy key to the remote project's user if applicable
    copy:
      src: "{{ flask_deploy_key_filepath }}"
      dest: "{{ deploy_key_filepath }}"
      owner: "{{ flask_user }}"
      mode: 0600

  when: "flask_deploy_key_filepath != ''"

- name: Install additional packages that could be required by the Flask app
  apt: name={{ item }} state=present
  with_items:
    - gettext
    - python3-venv
    - uwsgi
    - uwsgi-plugin-python
    - uwsgi-plugin-python3

- name: Add Python's deadsnakes repository
  apt_repository: repo="ppa:fkrull/deadsnakes"

- name: Install the python version required for the Flask application
  apt: name="{{ item }}" state=present
  with_items:
    - "{{ flask_python_version }}"
    - "{{ flask_python_version }}-dev"

- name: Ensure that the required folders exist
  file: path={{ item }} state=directory owner={{ flask_user }}
  with_items:
    - "{{ flask_path }}"
