---


- name: Create a uWSGI config file for the Flask project
  template: src=uwsgi.ini.j2 dest={{ flask_path }}/uwsgi.ini
  register: wsgi_config
  notify:
    - nginx restart

- name: Setup systemd service
  template:
    src: uwsgi.service.j2
    dest: "/etc/systemd/system/{{ flask_name }}-wsgi.service"
    owner: root
    group: root
    mode: 0644
  register: wsgi_service
  notify:
    - nginx restart

- name: Reload systemd
  shell: systemctl daemon-reload
  when: wsgi_service|changed

- name: Ensure that the uWSGI service is enabled
  service: "name={{ flask_name }}-wsgi enabled=yes"

- name: Restart the uWSGI service
  service: "name={{ flask_name }}-wsgi state=restarted"
  when: wsgi_service.changed or wsgi_config.changed
