---


- name: Create a virtualenv for the Flask project
  command: "/usr/bin/{{ flask_python_version}} -m venv --system-site-packages {{ flask_env_path }} creates={{ flask_env_path }}"

- name: Upgrade pip inside the newly created virtualenv
  pip:
    name: pip
    state: latest
    virtualenv: "{{ flask_env_path }}"

- name: Install project's requirements
  command: "{{ flask_env_path }}/bin/pip install -r {{ flask_requirements_file }}"
  register: pip_install_result
  changed_when: "'Successfully installed' in pip_install_result.stdout"

- include: trigger_reload.yml
  when: pip_install_result is changed
